
---

# =============================================================================
# Dependabot Configuration
# =============================================================================

version: 2

updates:

  # Git Submodule dependencies
  # ===========================================================================

  -
    package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-gitsubmodule"
      include: "scope"
    labels:
      - "dependencies"
      - "gitsubmodule"


  # GitHub Actions dependencies
  # ===========================================================================

  -
    package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-github-actions"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"


  # devContainer dependencies
  # ===========================================================================

  -
    package-ecosystem: "docker"
    directory: "/.devcontainer"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-devcontainer"
      include: "scope"
    labels:
      - "dependencies"
      - "devcontainer"

  -
    package-ecosystem: "devcontainers"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-devcontainer"
      include: "scope"
    labels:
      - "dependencies"
      - "devcontainer"


  # NPM dependencies
  # ===========================================================================

  -
    package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "08:00"
      timezone: "Europe/Amsterdam"
    target-branch: "dev"
    commit-message:
      prefix: "dependabot-npm"
      include: "scope"
    labels:
      - "dependencies"
      - "npm"
